spring.datasource.url=jdbc:postgresql://localhost:5432/career_match
spring.datasource.username=postgres
spring.datasource.password=Devbhargav@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true